apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-demo-mysql-pv
spec:
  storageClassName: db-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"