apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.k8sDemo.name.service }}
spec:
  selector:
    app: {{ .Values.k8sDemo.name.app }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.k8sDemo.service.http.port }}
      targetPort: {{ .Values.k8sDemo.service.http.targetPort }}
  type: ClusterIP
  