apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name.ingress}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # 需要安装 ingress-controller
  ingressClassName: {{ .Values.ingress.name.ingressClass}}
  rules:
    - host: {{ .Values.ingress.rule.host}}
      http:
        paths:
          - path: {{ .Values.ingress.rule.path}}
            pathType: {{ .Values.ingress.rule.pathType}}
            backend:
              service:
                name: {{ .Values.ingress.rule.service}}
                port:
                  number: {{ .Values.ingress.rule.targetPort}}
                