apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name.service }}
spec:
  selector:
    app: {{ .Values.mysql.name.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
      nodePort: {{ .Values.mysql.service.nodePort }}
  type: NodePort
  