apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.name.pv }}
spec:
  storageClassName: {{ .Values.mysql.name.storageClass }}
  capacity:
    storage: {{ .Values.mysql.volumes.storage }}
  accessModes: {{ .Values.mysql.volumes.accessModes }}
  hostPath:
    path: {{ .Values.mysql.volumes.hostPath }}