apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name.service}}
spec:
  selector:
    app: {{ .Values.redis.name.app}}
  ports:
    - protocol: TCP
      # k8s 内部访问接口
      port: {{ .Values.redis.service.port}}
      # 外部访问端口，必须在 30000-32767
      nodePort: {{ .Values.redis.service.nodePort}}
      # pod 暴露的端口
      targetPort: {{ .Values.redis.service.targetPort}}
  type: NodePort
  